### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by sangngoc27042001** [Onimee58/SolNET#1]
Dear Mr/Mrs,

My name is Sang, I am really interested in your work. However, I have checked the dataset and it is not as described in the paper. 

The paper tells that the dataset contains 2231 images (with 1130 images of the clean class and 1101 images of the dirty class). But, there are just 1440 images in the google drive link in total.

I hope that you could fix this, as I may need to refer your work for my thesis.

Best regards, 
Sang./.

**Comment by Onimee58** [comment]
Due to copyright issues, we only released (1435 +- 5) training set images. the entire dataset will be released with the subsequent publication no later than December 2023.
if you need to work on the dataset, I would suggest using image augmentation, which will provide you with near-similar results.
